# Generated by Django 5.0.6 on 2024-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(choices=[('oxapay', 'Oxapay')], default='oxapay', max_length=10, verbose_name='Gateway'),
        ),
    ]
