# Generated by Django 5.0.6 on 2024-06-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('offprice', models.IntegerField(default=0, verbose_name='Off Price')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Features')),
                ('thumbnail', models.ImageField(upload_to='products/product_thumbnails/', verbose_name='Thumbnail')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
